apiVersion: dapr.io/v1alpha1
kind: Resiliency
metadata:
  name: myresiliency
spec:
  policies:
    retries:
      pubsubRetry:
        policy: constant
        duration: 3s
        maxRetries: 3
  targets:
    components:
      pubsub: # Name of the component
        inbound:
          retry: pubsubRetry # Name of the retry policy
